services:
  - type: web
    name: indmoney-pulse-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
